-- DROP TABLE IF EXISTS area_info;
-- DROP TABLE IF EXISTS area_admin_level;
-- DROP TABLE IF EXISTS precinct_info;
-- DROP TABLE IF EXISTS senate_results;

CREATE TABLE IF NOT EXISTS area_info (
    code TEXT PRIMARY KEY,
    master_code TEXT,
    category_code INTEGER,
    name TEXT NOT NULL,
    FOREIGN KEY(master_code) REFERENCES area_info(code)
);

CREATE TABLE IF NOT EXISTS area_admin_level (
    code TEXT PRIMARY KEY,
    level INTEGER,
    FOREIGN KEY(code) REFERENCES area_info(code)
);

CREATE TABLE IF NOT EXISTS precinct_info (
    machine_id TEXT PRIMARY KEY,
    master_code TEXT NOT NULL,
    total_er_received INTEGER,
    location TEXT,
    voting_center TEXT,
    precinct_id TEXT,
    precincts_in_cluster TEXT,
    abstentions INTEGER,
    registered_voters  INTEGER NOT NULL,
    actual_voters INTEGER NOT NULL,
    valid_ballots INTEGER NOT NULL,
    FOREIGN KEY(master_code) REFERENCES area_info(code)
);

CREATE TABLE IF NOT EXISTS senate_results (
    machine_id TEXT PRIMARY KEY,
    c01_abalos INTEGER NOT NULL,
    c02_adonis INTEGER NOT NULL,
    c03_amad INTEGER NOT NULL,
    c04_andamo INTEGER NOT NULL,
    c05_aquino INTEGER NOT NULL,
    c06_arambulo INTEGER NOT NULL,
    c07_arellano INTEGER NOT NULL,
    c08_ballon INTEGER NOT NULL,
    c09_binay INTEGER NOT NULL,
    c10_bondoc INTEGER NOT NULL,
    c11_bong_revilla INTEGER NOT NULL,
    c12_bosita INTEGER NOT NULL,
    c13_brosas INTEGER NOT NULL,
    c14_cabonegro INTEGER NOT NULL,
    c15_capuyan INTEGER NOT NULL,
    c16_casiño INTEGER NOT NULL,
    c17_castro INTEGER NOT NULL,
    c18_cayetano INTEGER NOT NULL,
    c19_d_angelo INTEGER NOT NULL,
    c20_de_alban INTEGER NOT NULL,
    c21_de_guzman INTEGER NOT NULL,
    c22_dela_rosa INTEGER NOT NULL,
    c23_doringo INTEGER NOT NULL,
    c24_escobal INTEGER NOT NULL,
    c25_espiritu INTEGER NOT NULL,
    c26_floranda INTEGER NOT NULL,
    c27_gamboa INTEGER NOT NULL,
    c28_go INTEGER NOT NULL,
    c29_gonzales INTEGER NOT NULL,
    c30_hinlo INTEGER NOT NULL,
    c31_honasan INTEGER NOT NULL,
    c32_jose INTEGER NOT NULL,
    c33_lacson INTEGER NOT NULL,
    c34_lambino INTEGER NOT NULL,
    c35_lapid INTEGER NOT NULL,
    c36_lee INTEGER NOT NULL,
    c37_lidasan INTEGER NOT NULL,
    c38_marcoleta INTEGER NOT NULL,
    c39_marcos INTEGER NOT NULL,
    c40_marquez INTEGER NOT NULL,
    c41_martinez INTEGER NOT NULL,
    c42_mata INTEGER NOT NULL,
    c43_matula INTEGER NOT NULL,
    c44_maza INTEGER NOT NULL,
    c45_mendoza INTEGER NOT NULL,
    c46_montemayor INTEGER NOT NULL,
    c47_mustapha INTEGER NOT NULL,
    c48_olivar INTEGER NOT NULL,
    c49_ong INTEGER NOT NULL,
    c50_pacquiao INTEGER NOT NULL,
    c51_pangilinan INTEGER NOT NULL,
    c52_querubin INTEGER NOT NULL,
    c53_quiboloy INTEGER NOT NULL,
    c54_ramos INTEGER NOT NULL,
    c55_revillame INTEGER NOT NULL,
    c56_rodriguez INTEGER NOT NULL,
    c57_sahidulla INTEGER NOT NULL,
    c58_salvador INTEGER NOT NULL,
    c59_sotto INTEGER NOT NULL,
    c60_tapado INTEGER NOT NULL,
    c61_tolentino INTEGER NOT NULL,
    c62_tulfo INTEGER NOT NULL,
    c63_tulfo INTEGER NOT NULL,
    c64_valbuena INTEGER NOT NULL,
    c65_verceles INTEGER NOT NULL,
    c66_villar INTEGER NOT NULL,
    FOREIGN KEY(machine_id) REFERENCES precinct_info(machine_id)
);

-- Without ballot numbers, for convenience
CREATE VIEW IF NOT EXISTS senate_results2 AS
SELECT
    machine_id AS precinct,
    c01_abalos AS abalos,
    c02_adonis AS adonis,
    c03_amad AS amad,
    c04_andamo AS andamo,
    c05_aquino AS aquino,
    c06_arambulo AS arambulo,
    c07_arellano AS arellano,
    c08_ballon AS ballon,
    c09_binay AS binay,
    c10_bondoc AS bondoc,
    c11_bong_revilla AS bong_revilla,
    c12_bosita AS bosita,
    c13_brosas AS brosas,
    c14_cabonegro AS cabonegro,
    c15_capuyan AS capuyan,
    c16_casiño AS casino,
    c17_castro AS castro,
    c18_cayetano AS cayetano,
    c19_d_angelo AS d_angelo,
    c20_de_alban AS de_alban,
    c21_de_guzman AS de_guzman,
    c22_dela_rosa AS dela_rosa,
    c23_doringo AS doringo,
    c24_escobal AS escobal,
    c25_espiritu AS espiritu,
    c26_floranda AS floranda,
    c27_gamboa AS gamboa,
    c28_go AS go,
    c29_gonzales AS gonzales,
    c30_hinlo AS hinlo,
    c31_honasan AS honasan,
    c32_jose AS jose,
    c33_lacson AS lacson,
    c34_lambino AS lambino,
    c35_lapid AS lapid,
    c36_lee AS lee,
    c37_lidasan AS lidasan,
    c38_marcoleta AS marcoleta,
    c39_marcos AS marcos,
    c40_marquez AS marquez,
    c41_martinez AS martinez,
    c42_mata AS mata,
    c43_matula AS matula,
    c44_maza AS maza,
    c45_mendoza AS mendoza,
    c46_montemayor AS montemayor,
    c47_mustapha AS mustapha,
    c48_olivar AS olivar,
    c49_ong AS ong,
    c50_pacquiao AS pacquiao,
    c51_pangilinan AS pangilinan,
    c52_querubin AS querubin,
    c53_quiboloy AS quiboloy,
    c54_ramos AS ramos,
    c55_revillame AS revillame,
    c56_rodriguez AS rodriguez,
    c57_sahidulla AS sahidulla,
    c58_salvador AS salvador,
    c59_sotto AS sotto,
    c60_tapado AS tapado,
    c61_tolentino AS tolentino,
    c62_tulfo AS tulfo_ben,
    c63_tulfo AS tulfo_erwin,
    c64_valbuena AS valbuena,
    c65_verceles AS verceles,
    c66_villar AS villar
FROM senate_results;
